services:
  - type: web
    name: ndiscblockchaininfrastructure
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CONTRACT_ADDRESS
        value: 0x85Dbb2B7172A404ea302F66266F7Db19E47709C7
      - key: AMOY_RPC_URL
        value: https://rpc-amoy.polygon.technology
      - key: IPFS_GATEWAY
        value: https://gateway.pinata.cloud/ipfs
      - key: PUBLIC_APP_URL
        value: https://ndiscblockchaininfrastructure.onrender.com
      - key: PINATA_JWT
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_API_KEY
        sync: false
      - key: PRIVATE_KEY
        sync: false
